server:
  port: 3000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petshop
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true